import { StyleSheet } from "react-native";

export const colors = {
  bg: "#F4F0E6",
  panel: "#FFFCF6",
  ink: "#1C2418",
  muted: "#5C6756",
  line: "#D2C8B6",
  accent: "#2F6B4F",
  accent2: "#C45C26",
  danger: "#9B2C2C",
};

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.bg,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  brand: {
    fontSize: 28,
    fontWeight: "700",
    color: colors.ink,
    letterSpacing: -0.5,
  },
  brandAccent: { color: colors.accent },
  h1: {
    fontSize: 30,
    fontWeight: "700",
    color: colors.ink,
    letterSpacing: -0.6,
  },
  h2: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.ink,
    marginBottom: 10,
  },
  muted: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  balance: {
    fontSize: 42,
    fontWeight: "700",
    color: colors.ink,
    letterSpacing: -1,
    marginVertical: 6,
  },
  card: {
    backgroundColor: colors.panel,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
    marginBottom: 12,
  },
  input: {
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 12,
    color: colors.ink,
  },
  btn: {
    backgroundColor: colors.accent,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  btnText: { color: "#fff", fontWeight: "700", fontSize: 16 },
  btnSecondary: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  row: { flexDirection: "row", gap: 10, alignItems: "center" },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(47,107,79,0.12)",
  },
  chipText: { color: colors.accent, fontWeight: "600", fontSize: 13 },
  chipActive: { backgroundColor: colors.accent },
  chipActiveText: { color: "#fff", fontWeight: "600", fontSize: 13 },
  tabBar: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.panel,
    paddingBottom: 10,
    paddingTop: 8,
  },
  tabItem: { flex: 1, alignItems: "center", gap: 2 },
  tabLabel: { fontSize: 11, color: colors.muted, fontWeight: "600" },
  tabLabelActive: { color: colors.accent },
});
